# Generated by Django 4.2.24 on 2025-09-27 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('useremail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('lastupdate', models.DateTimeField(auto_now=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notetitle', models.CharField(max_length=255)),
                ('notecontent', models.TextField()),
                ('lastupdate', models.DateTimeField(auto_now=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.user')),
            ],
        ),
    ]
